//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.Cloud_CRUD_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="files", Namespace="http://schemas.datacontract.org/2004/07/Cloud_CRUD")]
    [System.SerializableAttribute()]
    public partial class files : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] dField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extention {
            get {
                return this.ExtentionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtentionField, value) != true)) {
                    this.ExtentionField = value;
                    this.RaisePropertyChanged("Extention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] d {
            get {
                return this.dField;
            }
            set {
                if ((object.ReferenceEquals(this.dField, value) != true)) {
                    this.dField = value;
                    this.RaisePropertyChanged("d");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user_details", Namespace="http://schemas.datacontract.org/2004/07/Cloud_CRUD")]
    [System.SerializableAttribute()]
    public partial class user_details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cloud_CRUD_Service.Operations")]
    public interface Operations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/GetConnectionString", ReplyAction="http://tempuri.org/Operations/GetConnectionStringResponse")]
        string GetConnectionString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/GetConnectionString", ReplyAction="http://tempuri.org/Operations/GetConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetConnectionStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Register", ReplyAction="http://tempuri.org/Operations/RegisterResponse")]
        int Register(string name, string pass, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Register", ReplyAction="http://tempuri.org/Operations/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(string name, string pass, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Login", ReplyAction="http://tempuri.org/Operations/LoginResponse")]
        int Login(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Login", ReplyAction="http://tempuri.org/Operations/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Add_File", ReplyAction="http://tempuri.org/Operations/Add_FileResponse")]
        int Add_File(string name, string Ext, byte[] d, int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Add_File", ReplyAction="http://tempuri.org/Operations/Add_FileResponse")]
        System.Threading.Tasks.Task<int> Add_FileAsync(string name, string Ext, byte[] d, int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Read_File", ReplyAction="http://tempuri.org/Operations/Read_FileResponse")]
        Web_Client.Cloud_CRUD_Service.files Read_File(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Read_File", ReplyAction="http://tempuri.org/Operations/Read_FileResponse")]
        System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.files> Read_FileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Fetch_All_Files", ReplyAction="http://tempuri.org/Operations/Fetch_All_FilesResponse")]
        Web_Client.Cloud_CRUD_Service.files[] Fetch_All_Files(int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Fetch_All_Files", ReplyAction="http://tempuri.org/Operations/Fetch_All_FilesResponse")]
        System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.files[]> Fetch_All_FilesAsync(int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/getUser", ReplyAction="http://tempuri.org/Operations/getUserResponse")]
        Web_Client.Cloud_CRUD_Service.user_details getUser(int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/getUser", ReplyAction="http://tempuri.org/Operations/getUserResponse")]
        System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.user_details> getUserAsync(int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Remove_File", ReplyAction="http://tempuri.org/Operations/Remove_FileResponse")]
        int Remove_File(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operations/Remove_File", ReplyAction="http://tempuri.org/Operations/Remove_FileResponse")]
        System.Threading.Tasks.Task<int> Remove_FileAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationsChannel : Web_Client.Cloud_CRUD_Service.Operations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationsClient : System.ServiceModel.ClientBase<Web_Client.Cloud_CRUD_Service.Operations>, Web_Client.Cloud_CRUD_Service.Operations {
        
        public OperationsClient() {
        }
        
        public OperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetConnectionString() {
            return base.Channel.GetConnectionString();
        }
        
        public System.Threading.Tasks.Task<string> GetConnectionStringAsync() {
            return base.Channel.GetConnectionStringAsync();
        }
        
        public int Register(string name, string pass, string email) {
            return base.Channel.Register(name, pass, email);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string name, string pass, string email) {
            return base.Channel.RegisterAsync(name, pass, email);
        }
        
        public int Login(string email, string pass) {
            return base.Channel.Login(email, pass);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string pass) {
            return base.Channel.LoginAsync(email, pass);
        }
        
        public int Add_File(string name, string Ext, byte[] d, int u) {
            return base.Channel.Add_File(name, Ext, d, u);
        }
        
        public System.Threading.Tasks.Task<int> Add_FileAsync(string name, string Ext, byte[] d, int u) {
            return base.Channel.Add_FileAsync(name, Ext, d, u);
        }
        
        public Web_Client.Cloud_CRUD_Service.files Read_File(int id) {
            return base.Channel.Read_File(id);
        }
        
        public System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.files> Read_FileAsync(int id) {
            return base.Channel.Read_FileAsync(id);
        }
        
        public Web_Client.Cloud_CRUD_Service.files[] Fetch_All_Files(int u) {
            return base.Channel.Fetch_All_Files(u);
        }
        
        public System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.files[]> Fetch_All_FilesAsync(int u) {
            return base.Channel.Fetch_All_FilesAsync(u);
        }
        
        public Web_Client.Cloud_CRUD_Service.user_details getUser(int u) {
            return base.Channel.getUser(u);
        }
        
        public System.Threading.Tasks.Task<Web_Client.Cloud_CRUD_Service.user_details> getUserAsync(int u) {
            return base.Channel.getUserAsync(u);
        }
        
        public int Remove_File(int id) {
            return base.Channel.Remove_File(id);
        }
        
        public System.Threading.Tasks.Task<int> Remove_FileAsync(int id) {
            return base.Channel.Remove_FileAsync(id);
        }
    }
}
